[mypy]
python_version = 3.11
warn_return_any = False
warn_unused_configs = True
ignore_missing_imports = True
pretty = True
exclude = (?x)(alembic|tests)
files = app

disable_error_code = attr-defined,call-arg,arg-type,assignment,operator,index,union-attr,return-value,var-annotated,import-untyped

[mypy-app.models.*]
ignore_errors = True
